# -*- coding: utf-8 -*-
"""program productivity

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LwqTRzKRDAc2UTX_Hv8mJQmF4lQqC5Dk
"""

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd



from transformers import pipeline
import pandas as pd

#Load sentiment analysis model
sentiment = pipeline("sentiment-analysis")
#Sample product review (you can change only text later)
reviews = """The laptop starts quickly and works smoothlyfor daily tasks.
The screen quality is clear and good for watching videos.
Battery backup is average and needs charging often.
The fan makes noise when manynapps are running.
Overall, it is a good laptop for students but not for gaining.
"""
# Split review into sentences
sentences = reviews.split(".")
pros = []
cons = []
for s in sentences:
  s = s.strip()
  if s == "":
    continue
  result = sentiment(s)[0]
  if result["label"] == "POSITIVE":
    pros.append(s)
  elif result["label"]== "NEGATIVE":
    cons.append(s)
# Take only 2 pros and 2 cons
pros = pros[:2]
cons = cons[:2]
# Create table
df = pd.DataFrame({
    "Pros": pros,
    "Cons": cons
})
df