# -*- coding: utf-8 -*-
"""TEXT GENERATION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hCIV5CsakAZ0wkiy4uSXuXCIH4yi0z6h
"""

!pip install transformers torch

#load text generation model(GenAI)
generator = pipeline(

    model="gpt2"
)
#input prompt
prompt = "Artficial Intelligence in finance will"
#Generate text
result = generator(prompt,max_length=50,num_return_sequences=1)
print("AI Generated text:")
print(result[0]["generated_text"])